### ISSUE TITLE
require_once(): Failed opening required '/usr/local/pkg/openbgpd.inc' on pfsense

### ISSUE THREAD

**Issue by lozlow** [travisghansen/kubernetes-pfsense-controller#25]
Hi there, I have had kpf set up and working brilliantly for many months but since yesterday I've started seeing a lot of errors like below from pfsense.

```
 PHP ERROR: Type: 64, File: /usr/local/www/xmlrpc.php(147) : eval()'d code, Line: 1, Message: require_once(): Failed opening required '/usr/local/pkg/openbgpd.inc' (include_path='.:/etc/inc:/usr/local/pfSense/include:/usr/local/pfSense/include/www:/usr/local/www:/usr/local/captiveportal:/usr/local/pkg:/usr/local/www/classes:/usr/local/www/classes/Form:/usr/local/share/pear:/usr/local/share/openssl_x509_crl/') @ 2023-06-16 17:19:59
```

After a bit of digging I saw that openbgpd was removed but that happened a while ago so I'm not sure why this would only just start happening.

I'm using pfsense version 2.6.0, metal-lb with the plugin setup:

```yaml
plugins:
  metallb:
    enabled: true
    nodeLabelSelector:
    nodeFieldSelector:
    bgp-implementation: openbgp
    options:
      openbgp:
        # pass through to config.xml
        template:
          md5sigkey:
          md5sigpass:
          groupname: metallb
          row:
            - parameters: announce all
              parmvalue:
  pfsense-dns-services:
    enabled: true
    serviceLabelSelector:
    serviceFieldSelector:
    #
    #allowedHostRegex: "/.*/"
    #
    dnsBackends:
      dnsmasq:
        enabled: false
      unbound:
        enabled: true
```

Do you have any pointers?
Thanks!
